# Generated by Django 3.2.8 on 2021-10-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='like'),
        ),
    ]
